# Development environment values for GitOps
# Uses dev-latest images from dev branch

replicaCount: 1

image:
  registry: acrnashpisharp.azurecr.io
  pullPolicy: Always

# Frontend configuration for Dev
frontend:
  enabled: true
  replicaCount: 1
  image:
    tag: "dev-latest"  # Latest from dev branch
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  autoscaling:
    enabled: false

# Backend configuration for Dev
backend:
  enabled: true
  replicaCount: 1
  image:
    tag: "dev-latest"  # Latest from dev branch
  env:
    - name: NODE_ENV
      value: "development"
    - name: PORT
      value: "3000"
    - name: MONGO_URL
      value: "mongodb://nash-pisharp-mongodb:27017/nashpisharp_dev"
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  autoscaling:
    enabled: false

# MongoDB configuration for Dev
mongodb:
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "default"

# Ingress configuration for Dev
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
  hosts:
    - host: dev.nash-pisharp.local
      paths:
        - path: /
          pathType: Prefix
          service: frontend
        - path: /api
          pathType: Prefix
          service: backend
  tls:
    - hosts:
        - dev.nash-pisharp.local
      secretName: nash-pisharp-dev-tls